appstudy/urls.py
# Django lib
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
""" students urls """

# Django
from django.urls import path

# Views
from users import views

urlpatterns = [
    path(
        route="",
        view=views.StudentMainView.as_view(),
        name="StudentMainView"
    ),
    path(
        route="list/",
        view=views.TeacherListView.as_view(),
        name="TeacherListView"
    ),
    path(
        route="select/",
        view=views.SelectionView.as_view(),
        name="select"
    ),
    path(
        route="maestro/",
        view=views.SignupTeacherView.as_view(),
        name="SignupAsTeacher"
    ),
    path(
        route="alumno/",
        view=views.SignupStudentView.as_view(),
        name="SignupAsStudent"
    ),
    path(
        route="login/",
        view=views.LoginView.as_view(),
        name="login"
    ),
    path(
        route="redirect/",
        view=views.redirection,
        name="redirect"
    ),
    path(
        route="colores/",
        view=views.game_colores,
        name="colores"
    ),
    path(
        route="abc/",
        view=views.game_abc.as_view(),
        name="abc"
    ),
    path(
        route="logout/",
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route="graph/",
        view=views.GraficoCalificacionesView.as_view(),
        name="graph"
    )
]

templates/grafico_calificaciones.html
{% load static %}

<img src="data:image/png;base64,{{ graph }}" alt="Gráfico de Calificaciones">
        <a class="btn-salir" href="{% url 'users:redirect' %}">Salir</a>

templates/magic.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="styles.css">
    <!-- Importación de fuente desde Google Fonts -->
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Comic+Sans+MS&display=swap');
    </style>
    <title>Interfaz de Juegos</title>
    <!-- Estilos CSS internos -->
    <style>
        /* Estilos generales */
        body {
            margin: 0;
            padding: 0;
            font-family: 'Comic Sans MS', cursive, sans-serif;
            background-image: url('{% static "img/mondo.jpg" %}');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            overflow-y: auto;
        }

        /* Estilos del encabezado */
        header {
            background-image: url('{% static "img/franja.jpg" %}');
            background-size: cover;
            background-position: center;
            color: white;
            text-align: center;
            padding: 20px;
            position: relative;
        }

        #logo {
            width: 290px;
            height: auto;
            margin: 0 auto;
        }

        /* Estilos del cuerpo principal */
        main {
            padding: 20px;
        }

        /* Estilos del contenedor de juegos */
        #juegos-container {
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            text-align: center;
        }

        /* Estilos para el botón de login */
        .login-button {
            padding: 10px 20px;
            font-size: 20px;
            background-color: rgb(0, 183, 255); 
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-top: 20px;
        }

        .eslogan {
            margin-top: 90px;
            font-size: 18px;
            color: #333;
        }

        /* Estilos para el contenedor de imágenes */
        .image-container {
            text-align: center;
            margin-top: 20px;
        }

        /* Estilos para las imágenes dentro del contenedor */
        .medium-image {
            display: block;
            max-width: 100%;
            height: auto;
            margin: 0 auto 10px;
        }

        /* Estilos para el carrusel */
        .carousel {
            max-width: 600px; /* Tamaño mediano */
            margin: 0 auto;
        }

        /* Estilo para las imágenes del carrusel */
        .carousel-inner img {
            max-height: 300px; /* Altura mediana */
        }

        /* Estilos para el menú */
        .navbar-nav {
            margin: 0 auto; /* Centra los elementos del menú */
            margin-top: 25px; /* Ajusta la posición vertical */
        }

        .navbar-nav .nav-item {
            margin-right: 10px; /* Espacio entre elementos del menú */
        }

        .navbar-brand {
            margin-right: 20px; /* Espacio a la derecha del texto "Menú" */
        }

        /* Estilo para el texto del menú */
        .navbar-nav .nav-link {
            font-size: 17px; /* Tamaño de fuente para el texto del menú */
            color: white !important; /* Color del texto del menú */
        }

        /* Estilo para el fondo del menú */
        .navbar-dark .navbar-nav .nav-link {
            background-color: #28B463 !important; /* Fondo del menú */
        }
    </style>
</head>
<body class="scrollable-body">
    <!-- Encabezado -->
    <header>
        <!-- Logo de la aplicación -->
        <img src="{% static 'img/magia.png' %}" alt="Logo" id="logo">
<a class="btn-cerrar_sesion" href="{% url 'users:logout' %}">Cerrar Sesion</a>
    </header>

    <!-- Navbar de Bootstrap -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #28B463 ; ">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <!-- Elementos del menú -->
                   
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Lenguaje
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'users:abc' %}">Abecedario</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Pensamiento Lógico <br> Matemático
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="Numeros.html">Números</a>
                            <a class="dropdown-item" href="Sumas.html">Sumas</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Creatividad 
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="artes.html">Artes visuales</a>
                            <a class="dropdown-item" href="#"></a>

                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Socioemocional
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="Socioemocional.html">Emociones</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Conocimiento <br> Del Entorno
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="Conocimiento_entorno.html">Cuidar el ambiente</a>
                            <a class="dropdown-item" href="Videos.html">Animales</a>

                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Autonomia Personal
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="Autonomia.html">valores</a>
                            <a class="dropdown-item" href="#"></a>

                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Ingles
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="numrs.HTML">Numeros</a>
                            <a class="dropdown-item" href="{% url 'users:colores' %}">Colores</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Cuerpo principal -->
    <main>
        <!-- Contenedor de juegos -->
        <div id="juegos-container">
            <!-- Eslogan de la aplicación -->
            <p class="eslogan">
                ¡Descubre el hechizo de aprender con MagicMin Academy!
                Donde cada juego es una llave mágica para desbloquear las competencias de lectura y escritura en los más pequeños.
                Nuestros juegos didácticos convierten cada desafío en una oportunidad para crecer. ¡Magia, diversión y aprendizaje en un solo lugar!
            </p>
            
                <!-- Imagen GIF -->
                <img src="https://i.gifer.com/origin/95/9592fe08911171b05f3c6aac39d0df83_w200.gif" alt="GIF Bangida" style="max-width: 100%;">
    

            <!-- Carrusel -->
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'img/imagen1.png' %}" class="d-block w-100" alt="Imagen 1">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/imagen2.png' %}" class="d-block w-100" alt="Imagen 2">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/imagen3.png' %}" class="d-block w-100" alt="Imagen 2">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/imagen4.png' %}" class="d-block w-100" alt="Imagen 2">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/imagen5.png' %}" class="d-block w-100" alt="Imagen 2">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'img/imagen6.png' %}" class="d-block w-100" alt="Imagen 2">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/teacherView.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lista de Alumnos</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
     body {
            margin: 0;
            padding: 0;
            font-family: 'Comic Sans MS', cursive, sans-serif;
            background-image: url('{% static "img/mondo.jpg" %}');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            overflow-y: auto;
        }

        /* Estilos del encabezado */
        header {
            background-image: url('{% static "img/franja.jpg" %}');
            background-size: cover;
            background-position: center;
            color: white;
            text-align: center;
            padding: 20px;
            position: relative;
        }

        #logo {
            width: 290px;
            height: auto;
            margin: 0 auto;
        }

        /* Estilos del cuerpo principal */
        main {
            padding: 20px;
        }

        /* Estilos del contenedor de juegos */
        #juegos-container {
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
            text-align: center;
        }

        /* Estilos para el botón de login */
        .login-button {
            padding: 10px 20px;
            font-size: 20px;
            background-color: rgb(0, 183, 255); 
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-top: 20px;
        }

    table {
      border-collapse: collapse;
      width: 100%;
      margin-top: 80px;
      background-color: #727e81; 
    }
    
    th {
      background-color: #6dd8f3; 
      color: #000000; 
    }
    
    td {
      background-color: #b7eff7; 
      color: #000000; 
    }
    
    th, td {
      border: 1px solid #000000; 
      padding: 10px;
      text-align: left;
    }
      
    .container {
      color: #101110; 
    }


        /* Estilo cuando se pasa el cursor sobre el botón */
        .btn-cerrar_sesion:hover {
            background-color: #e02c2c; /* Cambiar color de fondo */
        }

        /* Estilo cuando se presiona el botón */
        .btn-cerrar_sesion:active {
            background-color: #d61010; /* Cambiar color de fondo */
        }
    
  </style>
</head>
<body>
  <header>
    <!-- Logo de la aplicación -->
    <img src="{% static 'img/magia.png' %}" alt="Logo" id="logo">
            <a class="btn-cerrar_sesion" href="{% url 'users:logout' %}">Cerrar Sesion</a>

</header>

      <p>Codigo de maestro: {{ maestro.codigo_maestro }}</p>
  <div class="container">
    <h2 class="text-center">Lista de Alumnos</h2>
    <div class="table-responsive">

      <table id="alumnosTable" class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Promedio</th>
      <th>Recomendacion General</th>
    </tr>
  </thead>
  <tbody>
    {% for alumno in alumnos %}
    <tr>
      <td><a href="{% url 'users:graph' %}?a={{ alumno.0.user.username }}">{{ alumno.0.user.username }}</a></td>
      <td>
        <div style="display: flex; align-items: center;">
          <!-- <progress value="{{ alumno.calificacion }}" max="100" style="flex-grow: 1;"></progress> -->
          <span style="margin-left: 5px;">{{ alumno.1 }}</span>
        </div>
      </td>
      <td>
        <span>
          {% if alumno.1 >= 75 %}
            {{ recomendacion.General.0 }}
          {% elif alumno.1 >= 50 %}
            {{ recomendacion.General.1 }}
          {% elif alumno.1 >= 25 %}
            {{ recomendacion.General.2 }}
          {% elif alumno.1 >= 0 %}
            {{ recomendacion.General.3 }}
          {% endif %}
        </span>
      </td>
    </tr>
    {% endfor %}
    {% for alumno in alumnos_ %}
    <tr>
      <td>{{ alumno.user.username }}</td>
      <td>
        <div style="display: flex; align-items: center;">
          <span style="margin-left: 5px;">Sin revisar</span>
        </div>
      </td>
      <td></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>