appstudy/urls.py
# Django lib
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
""" students urls """

# Django
from django.urls import path

# Views
from users import views

urlpatterns = [
    path(
        route="",
        view=views.StudentMainView.as_view(),
        name="StudentMainView"
    ),
    path(
        route="list/",
        view=views.TeacherListView.as_view(),
        name="TeacherListView"
    ),
    path(
        route="select/",
        view=views.SelectionView.as_view(),
        name="select"
    ),
    path(
        route="maestro/",
        view=views.SignupTeacherView.as_view(),
        name="SignupAsTeacher"
    ),
    path(
        route="alumno/",
        view=views.SignupStudentView.as_view(),
        name="SignupAsStudent"
    ),
    path(
        route="login/",
        view=views.LoginView.as_view(),
        name="login"
    ),
    path(
        route="redirect/",
        view=views.redirection,
        name="redirect"
    ),
    path(
        route="colores/",
        view=views.game_colores,
        name="colores"
    ),
    path(
        route="abc/",
        view=views.game_abc.as_view(),
        name="abc"
    ),
    path(
        route="logout/",
        view=views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        route="graph/",
        view=views.GraficoCalificacionesView.as_view(),
        name="graph"
    )
]

users/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models

# Models

# Create your models here.
class Maestro(models.Model):
    """ Teacher model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    codigo_maestro = models.CharField(max_length=12, null=True)

class Materia(models.Model):
    """ Materia model """
    id_materia = models.AutoField(primary_key=True)
    nombre_materia = models.CharField(max_length=255)

class Alumno(models.Model):
    """ Student model """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nom_alumno = models.CharField(max_length=255)
    nom_padre = models.CharField(max_length=255)
    maestro = models.ForeignKey(Maestro, on_delete=models.CASCADE, null=True)

class Calif(models.Model):
    """ Califications models """
    id_calif = models.AutoField(primary_key=True)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE, null=True)
    calificacion = models.FloatField() #0 - 100

    class Meta:
        # Enforce unique constraint on alumno and materia fields together
        unique_together = ['alumno', 'materia']

users/forms.py
"""User forms."""

# Django
import random
import string
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Calif, Maestro, Alumno, Materia

class SignupTeacherForm(forms.Form):
    """Sign up form.
    Usable to register all user's type"""

    username = forms.CharField(min_length=4, max_length=36)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    ## to use later
    # first_name = forms.CharField(min_length=2, max_length=36)
    # last_name = forms.CharField(min_length=2, max_length=36)

    email = forms.EmailField(
        min_length=6,
        max_length=99,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('El nombre de usuario esta en uso')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        return data

    def save(self):
        """Create user and profile.
        
        args:
            type_user: type user class example Maestro
        """
        data = self.cleaned_data
        data.pop('password_confirmation')
        
        chars = string.ascii_letters + string.digits
        teacher_code = ''.join(random.choice(chars) for _ in range(10))

        user = User.objects.create_superuser(**data)
        profile = Maestro(user=user, codigo_maestro=teacher_code)
        profile.save()


class SignupStudentForm(forms.Form):
    """Sign up form.
    Usable to register all user's type"""

    username = forms.CharField(min_length=4, max_length=36)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    ## to use later
    # first_name = forms.CharField(min_length=2, max_length=36)
    # last_name = forms.CharField(min_length=2, max_length=36)

    email = forms.EmailField(
        min_length=6,
        max_length=99,
        widget=forms.EmailInput()
    )

    teacher_code = forms.CharField(
        max_length=12
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()

        if username_taken:
            raise forms.ValidationError('El nombre de usuario esta en uso')

        return username

    def clean(self):
        """Verify password confirmation match
        And must have a valid teacher code."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        teacher_code = data['teacher_code']
        valid_tc = Maestro.objects.filter(codigo_maestro=teacher_code)

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

        if not valid_tc:
            raise forms.ValidationError('Ingrese un codigo de maestro valido')

        return data

    def save(self):
        """Create user and profile.
        
        args:
            type_user: type user class example Maestro
        """
        data = self.cleaned_data
        data.pop('password_confirmation')

        teacher_code = data['teacher_code']
        maestro = Maestro.objects.get(codigo_maestro=teacher_code)
        data.pop('teacher_code')
        
        user = User.objects.create_user(**data)
        profile = Alumno(user=user, maestro=maestro)
        profile.save()


class ABCform(forms.Form):
    """ game form """
    calif = forms.IntegerField()

    def save(self, alumno, materia):
        """ Create new calification """
        data = self.cleaned_data

        calif = data['calif']
        print(calif)
        calif = Calif(alumno=alumno, materia=materia, calificacion=calif)
        calif.save()

users/views.py
""" User's views """


# External
import matplotlib.pyplot as plt
from json import dumps, loads
from math import ceil
from django.db.models import Avg
from io import BytesIO
import base64

# Django
from django import http
from django.forms import ValidationError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView
from django.templatetags.static import static

# Auth
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Mixins
from users.mixins import StudentRequiredMixin, TeacherRequiredMixin

# Urls
from django.urls import reverse, reverse_lazy

# Forms
from users.forms import SignupTeacherForm, SignupStudentForm, ABCform

# Models
from users.models import Calif, Materia, Maestro, Alumno

# settings
from appstudy.settings import STATIC_URL

# Const
SUCCESS_URL = 'users:login'
RECOM = loads(open(STATIC_URL + 'js/recom.json').read())

# Create your views here.
class SelectionView(TemplateView):
    """ Selection of type profile view
    
    ex: the teacher would select the teacher option
    """
    template_name = "users/selection.html"


class SignupTeacherView(FormView):
    """ Signup view for teacher type user """
    template_name = "users/teacherSignup.html"
    form_class = SignupTeacherForm
    success_url = reverse_lazy(SUCCESS_URL)

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class SignupStudentView(FormView):
    """ Signup view for teacher type user """
    template_name = "users/studentSignup.html"
    form_class = SignupStudentForm
    success_url = reverse_lazy(SUCCESS_URL)

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    """ Login view """
    template_name = 'users/login.html'


class StudentMainView(LoginRequiredMixin, TemplateView):
    """ Main view for students """
    template_name = 'magic.html'


class TeacherListView(TeacherRequiredMixin, TemplateView):
    """ Teacher main view """
    template_name = 'teacherView.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Query
        maestro = Maestro.objects.get(user=self.request.user)
        alumnos = Alumno.objects.filter(maestro=maestro)

        promedios_generales = []
        for alumno in alumnos:
            promedio_alumno = Calif.objects.filter(alumno=alumno).aggregate(promedio=Avg('calificacion'))['promedio']
            if promedio_alumno is None:
                promedio_alumno = 0
            promedios_generales.append((alumno, promedio_alumno))
        cal_alumnos = promedios_generales

        # cal_alumnos = Calif.objects.filter(alumno__maestro=maestro).select_related('alumno', 'materia')
        # alumnos = Alumno.objects.filter(maestro=maestro).values()
        # alumnos = Alumno.objects.filter(maestro=maestro, calif=None).exclude(calif=2).select_related('user')
        #
        context['alumnos'] = cal_alumnos
        # context['alumnos_'] = alumnos
        context['recomendacion'] = RECOM
        context['maestro'] = maestro

        return context


class LogoutView(LoginRequiredMixin, TemplateView):
    """ Logout current user """

    def get(self, request):
        logout(request)
        return redirect('users:login')

# Games Views
@login_required
def game_colores(request):
    """ Colores game """
    puntos = request.GET.get('puntos', '')

    try:
        nombre_materia = 'Ingles'

        materia = Materia.objects.get(nombre_materia=nombre_materia)
        alum_id = Alumno.objects.get(user=request.user.id)
        cal_alum = Calif.objects.get(alumno=alum_id, materia=materia).calificacion
        url_redirect = reverse('users:redirect')

        if cal_alum >= 75:
            ss = 0
        if cal_alum >= 50:
            ss = 1
        if cal_alum >= 25:
            ss = 2
        if cal_alum >= 0:
            ss = 3

        return HttpResponse(f"""Ya jugó este juego, su calificacion es: {cal_alum}, su recomendacion: {RECOM['Ingles'][ss]} <a href="{url_redirect}">atras</a>""")
    except (Calif.DoesNotExist, Materia.DoesNotExist):
        pass

    if puntos:
        print("aqui estan puntos", puntos)
        try:
            materia = Materia.objects.get(nombre_materia="Ingles").id_materia
            calif = Calif(alumno_id=request.user.alumno.id, materia_id=materia, calificacion=int(puntos))
            calif.save()

        except ValidationError:
            error_message = "Calificacion registrada"
            print(error_message)

    return render(request, 'games/Colores.html')


class game_abc(LoginRequiredMixin, FormView):
    """ ABC game view """
    template_name = 'games/formulario_juego.html'
    form_class = ABCform

    def get(self, request, *args, **kwargs):
        nombre_materia = 'Lenguaje'

        try:
            materia = Materia.objects.get(nombre_materia=nombre_materia)
            alumno = Alumno.objects.get(user=request.user)
            cal_alum = Calif.objects.get(alumno=alumno, materia=materia).calificacion

            if cal_alum >= 75:
                ss = 3
            if cal_alum >= 50:
                ss = 2
            if cal_alum >= 25:
                ss = 1
            if cal_alum >= 0:
                ss = 0

            url_redirect = reverse('users:redirect')
            return HttpResponse(f"""Ya jugó este juego, su calificacion es: {cal_alum}, su recomendacion: {RECOM['Lenguaje'][ss]} <a href="{url_redirect}">atras</a>""")
        except (Calif.DoesNotExist, Materia.DoesNotExist):
            pass
        return render(
            request=request,
            template_name=self.template_name,
            context={}
        )
    
    def get_success_url(self):
        return reverse_lazy('users:abc')


    def form_valid(self, form):
        nombre_materia = 'Lenguaje'

        alumno = Alumno.objects.get(user=self.request.user)
        materia = Materia.objects.get(nombre_materia=nombre_materia)
        form.save(alumno, materia)
        return super().form_valid(form)


@login_required
def redirection(request):
    if request.user.is_staff:
        return redirect("users:TeacherListView")
    return redirect("users:StudentMainView")

@login_required
def mostrar_usuario(request):
    """ Temporal """
    usuario = request.user
    data = {
        'username': usuario.username,
        'email': usuario.email
    }
    return JsonResponse(data)


class GraficoCalificacionesView(TemplateView):
    template_name = 'grafico_calificaciones.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        username = self.request.GET['a']
        user = User.objects.get(username=username)
        alumno = Alumno.objects.get(user=user)
        calificaciones = Calif.objects.filter(alumno=alumno)

        materias = [calif.materia.nombre_materia for calif in calificaciones]
        califs = [calif.calificacion for calif in calificaciones]

        plt.figure(figsize=(10, 5))
        plt.bar(materias, califs, color='skyblue')
        plt.xlabel('Materias')
        plt.ylabel('Calificaciones')
        plt.title('Calificaciones del Alumno')
        plt.xticks(rotation=0, ha='right')
        
        for i in range(len(materias)):
            plt.text(i, califs[i], f'{califs[i]:.2f}', ha='center', va='bottom')

        plt.ylim(0, 100)
        plt.tight_layout()

        buffer = BytesIO()
        plt.savefig(buffer, format='png')
        buffer.seek(0)
        image_png = buffer.getvalue()
        buffer.close()

        graph = base64.b64encode(image_png).decode()

        context['username'] = username
        context['graph'] = graph

        return context

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head_content %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    {% block container %}{% endblock%}
</body>
</html>

templates/users/baseLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head_content %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    {% block container %}{% endblock%}
</body>
</html>

templates/users/login.html
{% extends "users/base.html" %}
{% load static %}
{% block head_content %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <title>Login</title>
{% endblock %}
{% block container %}
    {% if form.errors %}
    <p class="alert alert-danger"> Error: Usuario o contraseña no validos </p>
    {% endif %}
    <div class="login-container">
        <h2><i class="fas fa-user-lock"></i>¡Bienvenido!</h2>
        <form method="POST" action="{% url 'users:login' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="correo" class="form-label"><i class="fas fa-user"></i>Nombre de usuario</label>
                <input type="text" class="form-control" id="nombre" name="username" required>
            </div>
            <div class="mb-3">
                <label for="contraseña" class="form-label"><i class="fas fa-lock"></i> Contraseña</label>
                <input type="password" class="form-control" id="contrasena" name="password" required>
            </div>

            <button type="submit" class="btn btn-primary"><i class="fas fa-sign-in-alt"></i> Ingresar</button>
        </form>

        <p class="footer-text">¿No tienes una cuenta? <a href="{% url 'users:select' %}">Regístrate aquí</a></p>
    </div>
{% endblock %}

templates/users/selection.html
{% load static %}

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MagicMind Academy</title>
    <style>
        body {
            background-image: url('{% static "img/mario.avif" %}');
            background-size: cover;
            background-position: center bottom;
            background-repeat: no-repeat;
            background-attachment: fixed;
            margin: 0;
        }

        .container {
            text-align: center;
            position: relative;
            margin-top: 370px; /* Ajusta el margen superior según tus necesidades */
        }

        .maestros-img,
        .alumnos-img,
        .imagen-superior {
            position: absolute;
            z-index: 1;
        }

        .maestros-img {
            top: -50px; /* Ajusta la posición vertical de la imagen de maestros */
            left: 25%; /* Ajusta la posición lateral de la imagen de maestros */
            transform: translateX(-50%);
            width: 200px; /* Ajusta el ancho de la imagen de maestros */
        }

        .alumnos-img {
            top: -50px; /* Ajusta la posición vertical de la imagen de alumnos */
            left: 45%; /* Ajusta la posición lateral de la imagen de alumnos para más separación */
            transform: translateX(-50%);
            opacity: 1;
            width: 200px; /* Ajusta el ancho de la imagen de alumnos */
        }

        .imagen-superior {
            top: -150px; /* Ajusta la posición vertical de la imagen superior */
            left: 50%; /* Ajusta la posición lateral de la imagen superior */
            transform: translateX(-50%);
            width: 300px; /* Ajusta el ancho de la imagen superior */
        }

        .boton {
            padding: 20px;
            border: none;
            background: none;
            cursor: pointer;
            margin-top: 20px; /* Ajusta el margen superior de los botones */
            position: relative;
            left: -300px; /* Ajusta el valor de left para mover los botones más hacia la izquierda */
            z-index: 0;
        }

        .boton + .boton {
            margin-left: 200px; /* Ajusta el margen izquierdo entre los botones */
        }

        .boton img {
            position: absolute;
            animation: floatAnimation 3s infinite ease-in-out;
            width: 180px;
        }

        @keyframes floatAnimation {
            0% {
                transform: translateY(0);
            }

            50% {
                transform: translateY(-90px);
            }

            100% {
                transform: translateY(0);
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Imagen de MAESTROS -->
        <img src="{% static 'img/maestros.png' %}" alt="texto" class="maestros-img">
        <!-- Imagen de ALUMNOS -->
        <img src="{% static 'img/ALUMNOS.png' %}" alt="texto" class="alumnos-img">
        <!-- Imagen superior -->
        <img src="{% static 'img/magia.png' %}" alt="Imagen superior" class="imagen-superior">
        <!-- Botón 1 con imagen -->
        <button class="boton">
            <a href="{% url 'users:SignupAsTeacher' %}">
                <img src="{% static 'img/caja.png' %}" alt="Botón 1">
            </a>
        </button>
        <!-- Botón 2 con imagen -->
        <button class="boton">
            <a href="{% url 'users:SignupAsStudent' %}">
                <img src="{% static 'img/caja.png' %}" alt="Botón 2">
            </a>
        </button>
    </div>
    <p class="footer-text">¿Tienes una cuenta? <a href="{% url 'users:login' %}">Entra aquí</a></p>
</body>

</html>

templates/users/studentLogin.html
{% extends "users/baseLogin.html" %}
{% load static %}
{% block head_content %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <title>Alumno login</title>
{% endblock %}
{% block container %}
    {#{% if form.errors %}{% endif%}#}
    <div class="login-container">
        <h2><i class="fas fa-user-lock"></i> Bienvenido Alumno!</h2>
        <form>
            {#{% csrf_token %}#}
            <div class="mb-3">
                <label for="nombre" class="form-label"><i class="fas fa-user"></i> Nombre del Alumno</label>
                <input type="text" class="form-control" id="nombre" name="nombre" required>
            </div>
            <div class="mb-3">
                <label for="contraseña" class="form-label"><i class="fas fa-lock"></i> Contraseña</label>
                <input type="password" class="form-control" id="contrasena" name="contrasena" required>
            </div>
            <div class="mb-3">
                <label for="escuela" class="form-label"><i class="fas fa-school"></i> Escuela</label>
                <input type="text" class="form-control" id="escuela" name="escuela" required>
            </div>
            
            <div class="mb-3">
                <label for="Grupo" class="form-label"><i class="fas fa-calendar-alt"></i> Grupo</label>
                <input type="text" class="form-control" id="Grupo" name="Grupo" required>
            </div>
            <div class="mb-3 text-center">
                <button type="submit" class="btn btn-primary"><i class="fas fa-sign-in-alt"></i> Ingresar</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/users/studentSignup.html
{% extends "users/base.html" %}
{% load static %}
{% block head_content %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <title>Maestro login</title>
{% endblock %}
{% block container %}
    {% if form.errors %}
    <p class="alert alert-danger"> Error las contraseñas no coinciden o ingreso un codigo de maestro no valido</p>
    {% endif %}
    <div class="login-container">
        <h2><i class="fas fa-user-lock"></i> Bienvenido Alumno!</h2>
        <form method="POST" action="{% url 'users:SignupAsStudent' %}">
            {% csrf_token %}

            <div class="mb-3">
                <label for="nombre" class="form-label"><i class="fas fa-user"></i> Nombre</label>
                <input type="text" class="form-control" id="nombre" name="username" minlength="6" required>
            </div>
            <div class="mb-3">
                <label for="correo" class="form-label"><i class="fas fa-user"></i> Correo</label>
                <input type="email" class="form-control" id="nombre" name="email" required>
            </div>
            <div class="mb-3">
                <label for="contraseña" class="form-label"><i class="fas fa-lock"></i> Contraseña</label>
                <input type="password" class="form-control" id="contrasena" name="password" required>
            </div>
            <div class="mb-3">
                <label for="contrasena" class="form-label"><i class="fas fa-lock"></i> Repetir contraseña</label>
                <input type="password" class="form-control" id="contrasena" name="password_confirmation" required>
            </div>
            <div class="mb-3">
                <label for="contrasena" class="form-label"><i class="fas fa-lock"></i> Codigo de maestro</label>
                <input type="text" class="form-control" id="codigo_maestro" name="teacher_code" required>
            </div>
            <button type="submit" class="btn btn-primary"><i class="fas fa-sign-in-alt"></i> Ingresar</button>
        </form>
        <a class="btn-salir" href="{% url 'users:redirect' %}">Salir</a>
    </div>
{% endblock %}

templates/users/teacherSignup.html
{% extends "users/base.html" %}
{% load static %}
{% block head_content %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <title>Maestro login</title>
{% endblock %}
{% block container %}
    {% if form.errors %}
    <p class="alert alert-danger"> Error las contraseñas no coinciden </p>
    {% endif %}
    <div class="login-container">
        <h2><i class="fas fa-user-lock"></i> Bienvenido Maestro!</h2>
        <form method="POST" action="{% url 'users:SignupAsTeacher' %}">
            {% csrf_token %}

            <div class="mb-3">
                <label for="nombre" class="form-label"><i class="fas fa-user"></i> Nombre</label>
                <input type="text" class="form-control" id="nombre" name="username" minlength="6" required>
            </div>
            <div class="mb-3">
                <label for="correo" class="form-label"><i class="fas fa-user"></i> Correo</label>
                <input type="email" class="form-control" id="nombre" name="email" required>
            </div>
            <div class="mb-3">
                <label for="contraseña" class="form-label"><i class="fas fa-lock"></i> Contraseña</label>
                <input type="password" class="form-control" id="contrasena" name="password" required>
            </div>
            <div class="mb-3">
                <label for="contrasena" class="form-label"><i class="fas fa-lock"></i> Repetir contraseña</label>
                <input type="password" class="form-control" id="contrasena" name="password_confirmation" required>
            </div>                
            <button type="submit" class="btn btn-primary"><i class="fas fa-sign-in-alt"></i> Ingresar</button>
        </form>
        <a class="btn-salir" href="{% url 'users:redirect' %}">Salir</a>
    </div>
{% endblock %}